parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\ApiSchemaResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    App\EventListener\ExceptionListener:
        arguments:
            $logger: '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Repository\ToDo\PointRepository:
        calls:
            - [ 'setLogger', [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: todo }

    App\Repository\ToDo\TaskRepository:
        calls:
            - [ 'setLogger', [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: todo }
